// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: beds.proto

package com.proto.beds;

public interface BedsAvailableResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hostpitalservicesbeds.BedsAvailableResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
