// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: beds.proto

package com.proto.beds;

public interface WelcomeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hostpitalservicesbeds.WelcomeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 number = 2;</code>
   */
  int getNumber();
}
