// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patients.proto

package com.proto.patients;

public interface CalculateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hostpitalservicespatients.CalculateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float number1 = 1;</code>
   */
  float getNumber1();

  /**
   * <code>float number2 = 2;</code>
   */
  float getNumber2();

  /**
   * <code>.hostpitalservicespatients.CalculateRequest.Operation operation = 3;</code>
   */
  int getOperationValue();
  /**
   * <code>.hostpitalservicespatients.CalculateRequest.Operation operation = 3;</code>
   */
  com.proto.patients.CalculateRequest.Operation getOperation();
}
