// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patients.proto

package com.proto.patients;

public interface ConvertMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hostpitalservicespatients.ConvertMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string number = 1;</code>
   */
  java.lang.String getNumber();
  /**
   * <code>string number = 1;</code>
   */
  com.google.protobuf.ByteString
      getNumberBytes();

  /**
   * <code>int32 fromBase = 2;</code>
   */
  int getFromBase();

  /**
   * <code>int32 toBase = 3;</code>
   */
  int getToBase();
}
