// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patients.proto

package com.proto.patients;

public interface NumberResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hostpitalservicespatients.NumberResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 number = 1;</code>
   */
  int getNumber();
}
