// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patients.proto

package com.proto.patients;

public interface NumberMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hostpitalservicespatients.NumberMessage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>float number = 1;</code>
   */
  float getNumber();
}
