// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patients.proto

package com.proto.patients;

public final class PatientsServiceImpl {
  private PatientsServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hostpitalservicespatients_ConvertMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hostpitalservicespatients_ConvertMessage_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hostpitalservicespatients_ConvertResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hostpitalservicespatients_ConvertResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hostpitalservicespatients_RandomRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hostpitalservicespatients_RandomRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hostpitalservicespatients_NumberResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hostpitalservicespatients_NumberResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hostpitalservicespatients_CalculateRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hostpitalservicespatients_CalculateRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hostpitalservicespatients_CalculateResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hostpitalservicespatients_CalculateResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_hostpitalservicespatients_NumberMessage_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_hostpitalservicespatients_NumberMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016patients.proto\022\031hostpitalservicespatie" +
      "nts\"B\n\016ConvertMessage\022\016\n\006number\030\001 \001(\t\022\020\n" +
      "\010fromBase\030\002 \001(\005\022\016\n\006toBase\030\003 \001(\005\"/\n\017Conve" +
      "rtResponse\022\016\n\006number\030\001 \001(\t\022\014\n\004base\030\002 \001(\005" +
      "\":\n\rRandomRequest\022\017\n\007numbers\030\001 \001(\005\022\013\n\003mi" +
      "n\030\002 \001(\005\022\013\n\003max\030\003 \001(\005\" \n\016NumberResponse\022\016" +
      "\n\006number\030\001 \001(\005\"\314\001\n\020CalculateRequest\022\017\n\007n" +
      "umber1\030\001 \001(\002\022\017\n\007number2\030\002 \001(\002\022H\n\toperati" +
      "on\030\003 \001(\01625.hostpitalservicespatients.Cal" +
      "culateRequest.Operation\"L\n\tOperation\022\014\n\010" +
      "ADDITION\020\000\022\017\n\013SUBTRACTION\020\001\022\022\n\016MULTIPLIC" +
      "ATION\020\002\022\014\n\010DIVISION\020\003\"4\n\021CalculateRespon" +
      "se\022\016\n\006result\030\001 \001(\002\022\017\n\007message\030\002 \001(\t\"\037\n\rN" +
      "umberMessage\022\016\n\006number\030\001 \001(\0022\306\003\n\017Patient" +
      "sService\022h\n\tcalculate\022+.hostpitalservice" +
      "spatients.CalculateRequest\032,.hostpitalse" +
      "rvicespatients.CalculateResponse\"\000\022p\n\025ge" +
      "nerateRandomNumbers\022(.hostpitalservicesp" +
      "atients.RandomRequest\032).hostpitalservice" +
      "spatients.NumberResponse\"\0000\001\022k\n\raverageV" +
      "alues\022(.hostpitalservicespatients.Number" +
      "Message\032,.hostpitalservicespatients.Calc" +
      "ulateResponse\"\000(\001\022j\n\013convertBase\022).hostp" +
      "italservicespatients.ConvertMessage\032*.ho" +
      "stpitalservicespatients.ConvertResponse\"" +
      "\000(\0010\001B+\n\022com.proto.patientsB\023PatientsSer" +
      "viceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_hostpitalservicespatients_ConvertMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_hostpitalservicespatients_ConvertMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hostpitalservicespatients_ConvertMessage_descriptor,
        new java.lang.String[] { "Number", "FromBase", "ToBase", });
    internal_static_hostpitalservicespatients_ConvertResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_hostpitalservicespatients_ConvertResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hostpitalservicespatients_ConvertResponse_descriptor,
        new java.lang.String[] { "Number", "Base", });
    internal_static_hostpitalservicespatients_RandomRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_hostpitalservicespatients_RandomRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hostpitalservicespatients_RandomRequest_descriptor,
        new java.lang.String[] { "Numbers", "Min", "Max", });
    internal_static_hostpitalservicespatients_NumberResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_hostpitalservicespatients_NumberResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hostpitalservicespatients_NumberResponse_descriptor,
        new java.lang.String[] { "Number", });
    internal_static_hostpitalservicespatients_CalculateRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_hostpitalservicespatients_CalculateRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hostpitalservicespatients_CalculateRequest_descriptor,
        new java.lang.String[] { "Number1", "Number2", "Operation", });
    internal_static_hostpitalservicespatients_CalculateResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_hostpitalservicespatients_CalculateResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hostpitalservicespatients_CalculateResponse_descriptor,
        new java.lang.String[] { "Result", "Message", });
    internal_static_hostpitalservicespatients_NumberMessage_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_hostpitalservicespatients_NumberMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_hostpitalservicespatients_NumberMessage_descriptor,
        new java.lang.String[] { "Number", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
