// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: patients.proto

package com.proto.patients;

public interface RandomRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hostpitalservicespatients.RandomRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 numbers = 1;</code>
   */
  int getNumbers();

  /**
   * <code>int32 min = 2;</code>
   */
  int getMin();

  /**
   * <code>int32 max = 3;</code>
   */
  int getMax();
}
